apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress-nginx
  labels:
    name: myingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - testing2.yogeshpawar.info
    secretName: tls-secret
  ingressClassName: nginx
  rules:
  - host: testing2.yogeshpawar.info
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service: 
            name: myapp
            port: 
              number: 80
