trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Terraforminit
  displayName: Terraform init
  pool: 
    vmImage= ubuntu-latest
  jobs:
  - job: Terraforminit
    displayName: Terraforminit
    pool: 
      vmImage: ubuntu-latest
    steps: 
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'pawanservice'
        backendAzureRmResourceGroupName: 'DoNotDeleteBackend'
        backendAzureRmStorageAccountName: 'backendsa4subho'
        backendAzureRmContainerName: 'pawancon'
        backendAzureRmKey: 'modules.terraform.tfstate'

    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'validate'


- stage: Terraformplan
  displayName: Terraform plan
  pool: 
    vmImage= ubuntu-latest
  jobs:
  - job: Terraformplan
    displayName: Terraform plan
    pool: 
      vmImage: ubuntu-latest
    steps: 
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'pawanservice'
        backendAzureRmResourceGroupName: 'DoNotDeleteBackend'
        backendAzureRmStorageAccountName: 'backendsa4subho'
        backendAzureRmContainerName: 'pawancon'
        backendAzureRmKey: 'modules.terraform.tfstate'