apiVersion: v1
kind: Pod
metadata:
  name: addtaskmicro
  labels:
    name: addtaskmicro
spec:
  containers:
    - name: addtaskmicro
      image: yugyogeshpawar/addtaskmicro
      ports:
        - containerPort: 8000
      env:
        - name: CONNECTION_STRING
          value: "Driver={ODBC Driver 17 for SQL Server};Server=tcp:monotodoapp.database.windows.net,1433;Database=yugdb;Uid=yug;Pwd=Yogesh@72448;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
