apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx-pod
spec:
  containers:
  - image: devopsinsiders/netflix-clone
    name: nginx-container
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"