# Create a new pod called web-pod with image busybox Allow the pod to be able to set system_time The container should sleep for 3200 seconds


apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - command:
    - sleep
    - "3000"
    image: busybox
    name: nginx
    resources: {}
    securityContext:
      capabilities:
        add: ["SYS_TIME"]
status: {}

