apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-get-task
  labels:
    app: gettask
  namespace: default
spec:
  replicas: 2
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - gettask
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: gettask
      name: micro-get-task
      namespace: default
    spec:
      containers:
        - name: micro-get-task
          image: yugyogeshpawar/gettaskmicro
          ports:
            - containerPort: 8000
          env:
            - name: CONNECTION_STRING
              value: "Driver={ODBC Driver 17 for SQL Server};Server=tcp:micro-db.database.windows.net,1433;Database=micro-db;Uid=adminuser;Pwd=Aduser@1234;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
            
