apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodedb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodedb-app
  template:
    metadata:
      labels:
        app: nodedb-app
    spec:
      containers:
        - name: nodedb-app
          image: philippaul/node-mongo-db:02
        - name : mongodb
          image: mongo
