apiVersion: apps/v1
kind: Deployment
metadata:
   labels:
     name: yogesh
   name: amar-yogesh
   namespace: default
spec:
   replicas: 5
   selector:
     matchExpressions:
       - key: name
         operator: In
         values: 
          - yogesh
   strategy: 
     type : RollingUpdate
     rollingUpdate : 
       maxSurge : 1
       maxUnavailable : 0
   template: 
     metadata:
      name: amar-yogesh
      labels:
        name: yogesh
     spec:
      containers:
      - name: ashish
        image: nginx
        ports:
          - containerPort: 80